### ISSUE TITLE
Ajedrez

### ISSUE THREAD

**Issue by FacuGsoria** [pdepmartestm/me-presento-dariodesalvo#1]
Sos bueno jugando? A mi me gusta tambien pero soy malismo

**Comment by dariodesalvo** [comment]
Estoy estudiando y entrenando, no tengo tanta experiencia. lichess.org/@/dari1989

**Comment by JJUAREZZ** [comment]
Utilizas chess.com tambien o solo lichess.org?

**Comment by dariodesalvo** [comment]
La cerré porque hay mucho modulero a nivel sub 2000 elo me parece.
